### ISSUE TITLE
Supplying className to toast overrides toastClassName of ToastContainer

### ISSUE THREAD

**Issue by itayganor** [fkhadra/react-toastify#457] opened 2020-04-18 00:33 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug. Or maybe request a feature. It depends on how you look on it

**What is the current behavior?**
```html
<ToastContainer toastClassName="general-toast"/>
```

```js
toast("lorem ipsum", {className: "special-variant"});
```

The result: the toast only has `special-variant`.

**What is the expected behavior?**

Class names should be appended, so: `general-toast special-variant`.
That way the user can design its project-wide toast with `general-toast` and apply variants by adding specific class names to specific toast emissions.

**Comment by fkhadra** [comment] 2020-04-18 09:27
Hey. Props defined on toast supersede ToastContainer's props. This is by design. 

I don't think that I'll add this feature. For the moment there is single rule: `Props defined on toast supersede ToastContainer's props`

If I allow this feature there would be 2 rules:
- Props defined on toast supersede ToastContainer's props
- Except for toastClassName. (This list could expand and I don't want that)

That said, I understand your concern. I think that there are many ways to solve your issue. 
For example, I would encapsulate the toast function:

```js
function myNotification(content, { className, ...options }) {
  return toast(content, {
    ...SHARED_OPTIONS,
    className: `${baseClassName} ${className || ''}`
   ...options
  })
}
```

**Comment by itayganor** [comment] 2020-04-18 11:16
I see why you don't want to allow exceptions to the current rule, but it's important to remember it's React, and it is expected by components to let the developer use `className="whatever"` without interfering the core features of the component.
If my `<Button/>` component has `className="btn"`, and it accepts `className` as a prop, it doesn't mean `btn` will be overridden, but classNames would be appended, like `className="btn whatever"`. That's the reason libraries like `classnames` and `clsx` exist and are so popular.
Because of this reason I deeply feel class names should be chained and not replaced.

**Comment by fkhadra** [comment] 2020-05-10 16:47
Hey, I'll close the issue. This is not something I intend to do right now. I've updated the documentation for the style. I may reconsider this feature if requested

**Closed by fkhadra** 2020-05-10 16:47 UTC
Labels: wontfix
