### ISSUE TITLE
Toast Update : not updating type, autoClose after using loading

### ISSUE THREAD

**Issue by vspassion007** [fkhadra/react-toastify#637] opened 2021-08-28 07:04 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
after I grab toast id from _toast.loading("blah blah")_
and then try to update like toast.update(toastId, {render: "yeah bruh", type: 'info', autoClose: 5000});
then only content is updated, type remains same and loading icon keeps showing :-(

Note: Same is happening on your demo page too. :-(

Also SandBox here : https://codesandbox.io/s/react-toastify-update-bug-u62im

**What is the expected behavior?**
Type and other options should update too

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16 and Chrome/Ubuntu

**Comment by fkhadra** [comment] 2021-08-30 15:13
Hey @vspassion007, actually this is by design. There is an issue with the documentation.

```tsx
const id = toast.loading("Please wait...")
//do something else
toast.update(id, { render: "All is good", type: "success", isLoading: false });
```
In the future, maybe I can think about inferring the loading state.

**Comment by fkhadra** [comment] 2021-08-30 15:14
I'll close the issue for now. I've updated the documentation, thanks for reporting the issue

**Closed by fkhadra** 2021-08-30 15:14 UTC
Labels: documentation

**Comment by vspassion007** [comment] 2021-08-30 15:30
@fkhadra Thanks for update, I created custome component usign promise to handle situation as promise is working as expected

**Comment by stefanprobst** [comment] 2022-01-19 17:39
@fkhadra could you clarify what properties `toast.update` will inherit from the toast container? i have found that, in addition to `isLoading: false` i also need to:

```js
toast.update(toastId, {
  render: "Success",
  type: "success",
  isLoading: false,
  autoClose: true,
  closeButton: true,
})
```

thanks!
