### ISSUE TITLE
error in react-toastify/libs/index.js:1 when running tests

### ISSUE THREAD

**Issue by abenhamdine** [fkhadra/react-toastify#228] opened 2018-08-29 21:04 UTC
Since upgrading to version 4.2.0 to version 4.2.2, when I run tests with ts-jest I get the following error : 

```
 /home/arhia/Documents/projects/payroll-app-next/client/node_modules/react-toastify/lib/index.js:1

 ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import ToastContainer from './components/ToastContainer';

  ^^^^^^^^^^^^^^
    
    SyntaxError: Unexpected identifier
```

ToastContainer seems properly exported/imported in that file, so I don't understand the meaning of this error.

Our configuration : 
"react-toastify": "4.2.2",
"react-scripts": "1.1.5"
"react-app-rewire-typescript": "2.0.2",
"react-app-rewired": "1.5.2",

Could someone provide some hints ?

**Comment by fkhadra** [comment] 2018-08-29 21:17
@abenhamdine did you upgrade any other dependencies like babel, babel-core ?

**Comment by abenhamdine** [comment] 2018-08-29 21:27
No, I'm still on babel 6.x, I didn't upgrade any of the babel suite : 
```
"babel-core": "6.26.3",
"babel-plugin-import": "1.8.0",
"babel-preset-react-app": "3.1.2",

**Comment by fkhadra** [comment] 2018-08-29 21:41
Can you delete the folder react-toastify under node_modules and reinstall it?

lib/index.js look normally like this:
```js
import ToastContainer from './components/ToastContainer';
import { Bounce, Slide, Zoom, Flip } from './components/Transitions';
import toast from './toast';
import cssTransition from './utils/cssTransition';
export { ToastContainer, toast, cssTransition, Bounce, Slide, Zoom, Flip };
```

**Comment by fkhadra** [comment] 2018-08-29 21:45
I'm able to reproduce the issue.

**Comment by fkhadra** [comment] 2018-08-29 21:51
Since I upgraded to babel7, I don't transform the `import` and `export` statement anymore.
I'll revert that behavior.

**Comment by fkhadra** [comment] 2018-08-29 22:02
@abenhamdine the issue is fixed now. 

👍

**Closed by fkhadra** 2018-08-29 22:02 UTC

**Comment by abenhamdine** [comment] 2018-08-29 22:09
thx a lot !
:+1: :dancer:
