### ISSUE TITLE
Toastify css webpack/chunk file not found(404) issue ( NextJS 14 & React 18.2.0 )

### ISSUE THREAD

**Issue by dltmdrbtjd** [fkhadra/react-toastify#1099] opened 2024-04-16 03:21 UTC
## Bug Report
**What is the current behavior?**
i got this issue. i use next.js version 14.2.1 & react version 18.2.0 & react-toastify 10.0.5
```
 GET /_next/static/css/ReactToastify.css.map 404 in 21ms
 GET /_next/static/chunks/app/react-toastify.esm.mjs.map 404 in 15ms
```
<img width="467" alt="스크린샷 2024-04-16 오후 12 15 27" src="https://github.com/fkhadra/react-toastify/assets/59644518/b8d3cef8-9796-4756-8b25-712133a99364">

If I import css from the root layout, the error above occurs. If I import css from root css, the first error disappears, but the error below still occurs.

Am I missing something?

**Comment by kamami** [comment] 2024-04-18 21:35
I have the same issue.

**Comment by douglasrcjames** [comment] 2024-04-18 21:47
Adding some context from my end here, getting the same issue when I updated to Next.js 14.2.1, but also occasionally getting the below error of `failed to pipe` on page load, and sometimes the page completely crashes. It should be noted that this is just on page load, not even actively calling a toast alert!

```
GET /_next/static/chunks/app/react-toastify.esm.mjs.map 404 in 101ms
Error: failed to pipe response
    at et (C:\Users\dougl\Documents\GitHub\mt-next-boiler\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:386705)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async er.pipeToNodeResponse (C:\Users\dougl\Documents\GitHub\mt-next-boiler\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:388154)
    at async sendRenderResult (C:\Users\dougl\Documents\GitHub\mt-next-boiler\node_modules\next\dist\server\send-payload.js:118:5)
    at async DevServer.pipeImpl (C:\Users\dougl\Documents\GitHub\mt-next-boiler\node_modules\next\dist\server\base-server.js:930:13)
    at async C:\Users\dougl\Documents\GitHub\mt-next-boiler\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\dougl\Documents\GitHub\mt-next-boiler\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\dougl\Documents\GitHub\mt-next-boiler\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\Users\dougl\Documents\GitHub\mt-next-boiler\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (C:\Users\dougl\Documents\GitHub\mt-next-boiler\node_modules\next\dist\server\lib\router-server.js:368:24)
    at async requestHandlerImpl (C:\Users\dougl\Documents\GitHub\mt-next-boiler\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (C:\Users\dougl\Documents\GitHub\mt-next-boiler\node_modules\next\dist\server\lib\start-server.js:141:13) {
  [cause]: TypeError [ERR_INVALID_STATE]: Invalid state: Unable to enqueue
      at transformStreamDefaultControllerEnqueue (node:internal/webstreams/transformstream:505:11)
      at TransformStreamDefaultController.enqueue (node:internal/webstreams/transformstream:323:5)
      at Object.flush (C:\Users\dougl\Documents\GitHub\mt-next-boiler\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:376892)
      at runNextTicks (node:internal/process/task_queues:60:5)
      at listOnTimeout (node:internal/timers:540:9)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'ERR_INVALID_STATE'
  }
}
```

**Comment by ViniciusCavalcanteSantos** [comment] 2024-05-01 13:09
anything new? having the same problem here.

**Comment by hubert-kniola** [comment] 2024-05-01 16:47
Tip from stack:

`@import '~react-toastify/dist/ReactToastify.min.css';
`
add this to globals.css file and the error will disappear

**Comment by ViniciusCavalcanteSantos** [comment] 2024-05-02 17:22
I had tried it before and it didn't work. Now I tried it again and it
worked. How I love programming! But thanks, man, you helped a lot.

**Comment by fullgream** [comment] 2024-05-02 17:26
> I had tried it before and it didn't work. Now I tried it again and it worked. How I love programming! But thanks, man, you helped a lot.

For me this didn't help

**Comment by dltmdrbtjd** [comment] 2024-05-03 17:22
hmmm.... It's not exact, but I suspect it seems to be unable to be read due to a problem in the bundling process of react-toastify scss when building in nextjs.

**Comment by marcustran98** [comment] 2024-05-15 09:18
i have the same issue

**Comment by ganny0219** [comment] 2024-05-20 01:33
i put import "react-toastify/dist/ReactToastify.css"; on layout.tsx folder an this is working for me

**Comment by kyawnyeinnaing-lastoenjob** [comment] 2024-05-23 12:02
remove `dist`, it should be like that `import 'react-toastify/ReactToastify.min.css';`. I don't get the error anymore
`"react-toastify": "^10.0.5"`
`"next": "14.2.3"`

**Comment by fullgream** [comment] 2024-05-23 17:19
**Issue Description:**
I'm encountering 404 errors related to React Toastify after trying several troubleshooting steps.

**Steps I've taken:**
1. Removed `node_modules`
2. Removed `.next`
3. Reinstalled all dependencies
4. Added the following import statement:
   ```javascript
   import 'react-toastify/ReactToastify.min.css';

With dependencies versions:

	•	"react-toastify": "^10.0.5"
	•	"next": "^14.2.3"

Errors Encountered:
Despite the above steps, I’m still facing 404 errors for certain resources:
```
GET /_next/static/chunks/app/react-toastify.esm.mjs.map 404 in 12ms
GET /_next/static/chunks/app/platform/react-toastify.esm.mjs.map 404 in 14ms
GET /_next/static/chunks/app/platform/react-toastify.esm.mjs.map 404 in 11ms
```

**Comment by marcasmed** [comment] 2024-05-25 09:03
> I'm encountering 404 errors related to React Toastify after trying several troubleshooting steps.
> 
> **Steps I've taken:**
> 
> 1. Removed `node_modules`
> 2. Removed `.next`
> 3. Reinstalled all dependencies
> 4. Added the following import statement:
>    ```js
>    import 'react-toastify/ReactToastify.min.css';
>    ```
> 
> With dependencies versions:
> 
> ```
> •	"react-toastify": "^10.0.5"
> •	"next": "^14.2.3"
> ```
> 
> Errors Encountered: Despite the above steps, I’m still facing 404 errors for certain resources:
> 
> ```
> GET /_next/static/chunks/app/react-toastify.esm.mjs.map 404 in 12ms
> GET /_next/static/chunks/app/platform/react-toastify.esm.mjs.map 404 in 14ms
> GET /_next/static/chunks/app/platform/react-toastify.esm.mjs.map 404 in 11ms
> ```

Try importing it into the layout.tsx file.
I was having the same issue when I imported to a page.tsx file

**Comment by douglasrcjames** [comment] 2024-05-29 17:34
> remove `dist`, it should be like that `import 'react-toastify/ReactToastify.min.css';`. I don't get the error anymore `"react-toastify": "^10.0.5"` `"next": "14.2.3"`

This plus placing the import in the main `layout.tsx` file seemed to work for me

**Comment by humanterror** [comment] 2024-06-03 20:47
> > I'm encountering 404 errors related to React Toastify after trying several troubleshooting steps.
> > **Steps I've taken:**
> > 
> > 1. Removed `node_modules`
> > 2. Removed `.next`
> > 3. Reinstalled all dependencies
> > 4. Added the following import statement:
> >    ```js
> >    import 'react-toastify/ReactToastify.min.css';
> >    ```
> > 
> > With dependencies versions:
> > ```
> > •	"react-toastify": "^10.0.5"
> > •	"next": "^14.2.3"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Errors Encountered: Despite the above steps, I’m still facing 404 errors for certain resources:
> > ```
> > GET /_next/static/chunks/app/react-toastify.esm.mjs.map 404 in 12ms
> > GET /_next/static/chunks/app/platform/react-toastify.esm.mjs.map 404 in 14ms
> > GET /_next/static/chunks/app/platform/react-toastify.esm.mjs.map 404 in 11ms
> > ```
> 
> Try importing the css into the `layout.tsx` file.
> 
> [This example](https://fkhadra.github.io/react-toastify/installation/#the-gist) in the main docs is a bit outdated for Next 14. Split the imports:
> 
> ```ts
> // layout.tsx
> import "react-toastify/ReactToastify.css";
> 
> // page.tsx
> import { ToastContainer } from "react-toastify";
> 
> // button-component.tsx
> "use client";
> import { toast } from "react-toastify";
> import { FaRegCopy } from "react-icons/fa6";
> 
> const CopyButton = () => {
>   const handleCopy = () => {
>     navigator.clipboard.writeText("test");
>     toast("Report copied to clipboard!");
>   };
> 
>   return (
>     <button onClick={handleCopy}>
>       <FaRegCopy className="w-5 h-5 p-1" />
>     </button>
>   );
> };
> ```
> 
> _Update: formatting and examples_

It didn't work for me.

**Comment by spacecat** [comment] 2024-06-09 18:23
I'm experiencing the same issue:

    ~/repos  on   main  npm run dev                                                                                     ✔  took 1h 34m 9s   at 20:02:26  

> blah@0.1.0 dev
> next dev

  ▲ Next.js 14.2.3
  - Local:        http://localhost:3000
  - Environments: .env.local

 ✓ Starting...
 ✓ Ready in 1688ms
 ✓ Compiled /middleware in 391ms (169 modules)
 ○ Compiling /dashboard ...
 ✓ Compiled /dashboard in 3.8s (1559 modules)
 ✓ Compiled in 558ms (620 modules)
 GET /dashboard 200 in 4359ms
 ○ Compiling /_not-found ...
 ✓ Compiled /favicon.ico in 2.5s (1553 modules)
 GET /_next/static/chunks/app/react-toastify.esm.mjs.map 404 in 2687ms
 GET /_next/static/chunks/app/dashboard/react-toastify.esm.mjs.map 404 in 2549ms
 GET /favicon.ico 200 in 2175ms
 POST /dashboard 200 in 2365ms
 POST /dashboard 200 in 101ms

**Comment by KarsonJo** [comment] 2024-06-10 12:56
Same issue, any updates?

**Comment by douglasrcjames** [comment] 2024-06-10 20:20
> > remove `dist`, it should be like that `import 'react-toastify/ReactToastify.min.css';`. I don't get the error anymore `"react-toastify": "^10.0.5"` `"next": "14.2.3"`
> 
> This plus placing the import in the main `layout.tsx` file seemed to work for me

Updating that what I thought fixed my issue, actually does not, and this bug still is very much annoying in my logs! considering just switching libs.

**Comment by BorisBarzotto** [comment] 2024-06-15 02:54
Hi, It happened to me again, at first I thought it had been solved with that import suggestion in layout.tsx but it's still the same issue.

NextJS 14.2.3
ReactToastify 9.1.3
These are the messages I see repeatedly in the console and my notifications still work but it sends many 404 messages.

``` GET /favicon.ico 200 in 3491ms
 GET /_next/static/chunks/app/dashboard/sales/simple-invoices/react-toastify.esm.mjs.map 404 in 725ms
 GET /dashboard/sales/simple-invoices 200 in 7424ms
 GET /favicon.ico 200 in 218ms
 GET /_next/static/css/app/ReactToastify.css.map 404 in 204ms
 GET /_next/static/chunks/app/react-toastify.esm.mjs.map 404 in 215ms
 GET /_next/static/chunks/app/dashboard/sales/simple-invoices/react-toastify.esm.mjs.map 404 in 91ms
 GET /_next/static/chunks/app/dashboard/sales/simple-invoices/react-toastify.esm.mjs.map 404 in 128ms
 POST /dashboard/sales/simple-invoices 200 in 2462ms
 GET /_next/static/css/app/ReactToastify.css.map 404 in 118ms
 ○ Compiling /dashboard/customers ...
 ✓ Compiled /dashboard/customers in 4.2s (3815 modules)
 GET /_next/static/chunks/app/dashboard/customers/react-toastify.esm.mjs.map 404 in 241ms
 ○ Compiling /api/auth/sign-out ...
 ✓ Compiled /api/auth/sign-out in 1235ms (3653 modules)
 POST /api/auth/sign-out 301 in 4188ms
 GET /login 200 in 439ms
 GET /_next/static/css/app/ReactToastify.css.map 404 in 172ms
 GET /_next/static/chunks/app/react-toastify.esm.mjs.map 404 in 202ms```

**Comment by simba0808** [comment] 2024-06-17 07:51
Has this issue been resolved?
I have same issue on React Toastify(10.0.5).

`GET /_next/static/chunks/app/(main)/artwork/%5Bslug%5D/react-toastify.esm.mjs.map 404 in 75ms
 GET /_next/static/chunks/app/react-toastify.esm.mjs.map 404 in 66ms`

If anyone has a solution, I would love to hear your answer.

**Comment by andre-vg** [comment] 2024-06-18 23:23
I'm having the same issue, same version used but seems like if you run your project with turbopack enabled, the issue disapear!!

**Comment by stevensa1** [comment] 2024-06-21 02:23
> I'm having the same issue, same version used but seems like if you run your project with turbopack enabled, the issue disapear!! https://nextjs.org/docs/architecture/turbopack

Thanks! at least it doesn't spam the logs

**Comment by zonterone** [comment] 2024-06-25 08:13
Same issue

```
    "next": "^14.2.4",
    "react-toastify": "^10.0.5",
```

**Comment by Shashankch14** [comment] 2024-07-04 17:49
Same `Issue`

**

> GET /_next/static/chunks/app/pages/addworkout/react-toastify.esm.mjs.map 404 in 403ms
>  GET /_next/static/chunks/app/react-toastify.esm.mjs.map 404 in 396ms

**

**Comment by Zerebokep** [comment] 2024-07-09 10:03
Same error here, marcasmed's solution didn't work for me (errors are still there).

**Comment by Kila14** [comment] 2024-07-10 08:45
Same issue
`    "next": "^14.2.4",
    "react-toastify": "^10.0.5",`

**Comment by totorofly** [comment] 2024-07-14 00:34
Same issue
```
     "next": "^14.2.5",
     "react-toastify": "^10.0.5",
```

**Comment by Anil-Kyurius** [comment] 2024-07-18 04:26
same issue

**Comment by casaumayman** [comment] 2024-07-18 06:24
Same issue

**Comment by Dupflo** [comment] 2024-07-19 09:05
> https://nextjs.org/docs/architecture/turbopack

Luckily it worked for me

**Comment by Dupflo** [comment] 2024-07-19 09:06
> > I'm encountering 404 errors related to React Toastify after trying several troubleshooting steps.
> > **Steps I've taken:**
> > 
> > 1. Removed `node_modules`
> > 2. Removed `.next`
> > 3. Reinstalled all dependencies
> > 4. Added the following import statement:
> >    ```js
> >    import 'react-toastify/ReactToastify.min.css';
> >    ```
> > 
> > With dependencies versions:
> > ```
> > •	"react-toastify": "^10.0.5"
> > •	"next": "^14.2.3"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Errors Encountered: Despite the above steps, I’m still facing 404 errors for certain resources:
> > ```
> > GET /_next/static/chunks/app/react-toastify.esm.mjs.map 404 in 12ms
> > GET /_next/static/chunks/app/platform/react-toastify.esm.mjs.map 404 in 14ms
> > GET /_next/static/chunks/app/platform/react-toastify.esm.mjs.map 404 in 11ms
> > ```
> 
> Try importing the css into the `layout.tsx` file.
> 
> [This example](https://fkhadra.github.io/react-toastify/installation/#the-gist) in the main docs is a bit outdated for Next 14. Split the imports:
> 
> ```ts
> // layout.tsx
> import "react-toastify/ReactToastify.css";
> 
> // page.tsx
> import { ToastContainer } from "react-toastify";
> 
> // button-component.tsx
> "use client";
> import { toast } from "react-toastify";
> import { FaRegCopy } from "react-icons/fa6";
> 
> const CopyButton = () => {
>   const handleCopy = () => {
>     navigator.clipboard.writeText("test");
>     toast("Report copied to clipboard!");
>   };
> 
>   return (
>     <button onClick={handleCopy}>
>       <FaRegCopy className="w-5 h-5 p-1" />
>     </button>
>   );
> };
> ```
> 
> _Update: formatting and examples_

Luckily it worked for me

**Comment by Dupflo** [comment] 2024-07-19 09:09
Same issue...

**Comment by niiima** [comment] 2024-07-22 21:44
Just upgraded to new version of Next.js and the error appeared:
`"next": "^14.2.5",
"react-toastify": "^10.0.5",`
And the error exist
` 
 GET /_next/static/css/app/ReactToastify.css.map 404 in 1706ms
 GET /_next/static/chunks/app/react-toastify.esm.mjs.map 404 in 143ms
`

**Comment by Appolinars** [comment] 2024-07-26 15:11
![image](https://github.com/user-attachments/assets/0c5029eb-afd1-4b90-abe6-86b793663593)
Facing the same after we updated Next and react-toastify to latest versions today
"next": "^14.2.5",
"react-toastify": "^10.0.5",
Any solutions?

**Comment by Sergiy5** [comment] 2024-07-31 09:56
I fixed This issue, just copy this files from node_moduls/react-toastify/dist/react-toastify.esm.mjs.map and ReactToastify.css.map. Then copy and put in folder "/_next/static/chunks/app/" and accordingly "/_next/static/css/app/" where they are lacking.

**Comment by hqw567** [comment] 2024-08-07 08:36
Same issue

**Comment by mtahagocer** [comment] 2024-08-08 11:47
In a Next.js 14 project utilizing the App Router, I faced a similar challenge. Initially, I imported `react-toastify/dist/ReactToastify.css` directly within the **layout.tsx** file, which resulted in a warning. To resolve this, I moved the import statement to the global CSS file, using `@import '~react-toastify/dist/ReactToastify.min.css';` . 

This adjustment eliminated the warning.


// app/globals.css

`@import '~react-toastify/dist/ReactToastify.min.css';`

**Comment by Kila14** [comment] 2024-08-08 13:49
There is still an error with this:
`react-toastify.esm.mjs.map 404`

**Comment by Sergiy5** [comment] 2024-08-09 07:42
After reload VSC i have error again...

**Comment by casaumayman** [comment] 2024-08-09 07:44
I have switched to react-hot-toast instead. It works fine with NextJS.

**Comment by andre-vg** [comment] 2024-08-09 13:26
> I have switched to react-hot-toast instead. It works fine with NextJS.

I highly recommend using [Sonner](https://github.com/emilkowalski/sonner), the migration from react-toastify is straightforward!!

**Comment by spacecat** [comment] 2024-08-10 11:51
> > I have switched to react-hot-toast instead. It works fine with NextJS.
> 
> I highly recommend using [Sonner](https://github.com/emilkowalski/sonner), the migration from react-toastify is straightforward!!

If someone makes a comprehensive react-toastify vs sonner I'll consider it ;)

It's being adopted rapidly:

https://npmtrends.com/react-toastify-vs-sonner

**Comment by berci-i** [comment] 2024-09-09 16:47
same error here :(

**Comment by Sergiy5** [comment] 2024-09-11 13:19
No I am ignore it by now

**Comment by princekumar205086** [comment] 2024-09-22 22:01
I am facing the same issue in nextjs 14 app. 

i am able to fix using:

    `yarn upgrade` 

if using npm use:

    `npm update`

and then paste this in global.css and remove you import for css first

    `@import '~react-toastify/ReactToastify.min.css';`

**Comment by Sergiy5** [comment] 2024-09-24 10:31
I still have errors: GET /_next/static/chunks/app/(admin)/react-toastify.esm.mjs.map 404 in 1039ms
 GET /_next/static/chunks/app/(admin)/home/react-toastify.esm.mjs.map 404 in 958ms
 GET /_next/static/chunks/app/(admin)/auth/react-toastify.esm.mjs.map 404 in 1049ms
 GET /_next/static/chunks/app/react-toastify.esm.mjs.map 404 in 1051ms
 GET /_next/static/chunks/app/(admin)/%5Bmovies%5D/react-toastify.esm.mjs.map 404 in 955ms

**Comment by jvivasb20** [comment] 2024-09-26 02:01
Any updates for this? i'm facing the same issue.

**Comment by QingjiaTsang** [comment] 2024-10-02 06:05
the same error occurred to me, and I have tried all the solutions above, ending up in failure.

"next": "14.2.10",
"react-toastify": "^10.0.5",

**Comment by Jeff92316046** [comment] 2024-10-03 04:04
same issue

**Comment by R3flector** [comment] 2024-10-09 07:41
same error 
  "react-toastify": "^10.0.5",
  "next": "latest",

**Comment by jeffigy** [comment] 2024-10-09 12:57
> same error "react-toastify": "^10.0.5", "next": "latest",

Same here, I just went with Sonner. It's pretty much the same implementation.

**Comment by MilanCiprian** [comment] 2024-10-09 21:08
# Issue with 404 Errors for Source Map Files in react-toastify
If you're encountering 404 errors in the console for source map files like react-toastify.esm.mjs.map and react-toastify.js.map, you're not alone. This issue arises when the browser attempts to load the source maps that are referenced at the end of the minified JavaScript files. Here's how to resolve this problem:

## Background
When using libraries like react-toastify, the compiled JavaScript files often include a reference to a source map file at the end, which looks like this:

```
//# sourceMappingURL=react-toastify.esm.mjs.map
```
These source maps are intended to help with debugging by mapping the minified code back to the original source code. However, if the source map files are not available in the expected location, the browser will log a 404 error in the console.

## Steps to Resolve the Issue
1. **Locate the Files:** Navigate to the `node_modules/react-toastify/dist` directory in your project. You will find the files `react-toastify.esm.mjs` and `react-toastify.js`.

2. **Edit the Files:** Open both `react-toastify.esm.mjs` and `react-toastify.js` files in a text editor.

3. **Remove the Source Map Reference:** At the end of each of these files, you will find the line that references the source map:
```
//# sourceMappingURL=react-toastify.esm.mjs.map
```
Remove this line from both files. This will prevent the browser from trying to load the missing source map files and eliminate the 404 errors from the console.

4. **Save Your Changes:** After editing, save the files.

5. **Rebuild Your Project:** Stop the development server, delete the `.next` folder, and then start the server again to ensure the changes take effect.

## Important Note
Modifying files within `node_modules` is generally not recommended, as they can be overwritten when the package is updated. Consider creating a script or a post-installation hook to automate this process in the future. Additionally, keep an eye on updates to the react-toastify library, as this issue may be resolved in newer versions.

**Comment by Kila14** [comment] 2024-10-10 05:42
> # Issue with 404 Errors for Source Map Files in react-toastify

Maybe the better solution is to pull request this?

**Comment by douglasrcjames** [comment] 2024-10-12 21:41
I switched to Sonner toast library to resolve this. Was also getting a few other minor issues, so we will see how I like sonner.

**Comment by fkhadra** [comment] 2024-10-12 22:16
Hey, anybody able to provide a repository with the issue? I'm not able to trigger the issue, i have a fresh repo with next `14.2.15`.

**Comment by dunfe** [comment] 2024-10-17 01:33
Same issue

**Comment by fkhadra** [comment] 2024-10-17 01:35
If I could get my hand on a repository or a codesanbox with the issue it would be solved rather quickly, anybody?

**Comment by nicolo-tito** [comment] 2024-10-17 09:19
@fkhadra I used to notice the problem for quite some time with previous Next versions, but it looks like it doesn't show anymore from 14.2.15 for me as well

**Comment by Dupflo** [comment] 2024-10-18 07:22
Yes in 14.2.15, the error does not occur anymore

**Comment by Kila14** [comment] 2024-10-18 07:41
> Yes in 14.2.15, the error does not occur anymore

The error still occurs.

package.json:
> {
>   "name": "jackdaw",
>   "version": "0.1.0",
>   "private": true,
>   "scripts": {
>     "dev": "next dev -p 3005",
>     "build": "prisma generate && next build",
>     "start": "next start",
>     "lint": "next lint"
>   },
>   "dependencies": {
>     "@prisma/client": "^5.21.0",
>     "animate.css": "^4.1.1",
>     "mobx": "^6.13.5",
>     "mobx-react-lite": "^4.0.7",
>     "next": "^14.2.15",
>     "react": "^18.3.1",
>     "react-dom": "^18.3.1",
>     "react-toastify": "^10.0.6",
>     "zod": "^3.23.8"
>   },
>   "devDependencies": {
>     "@types/node": "^22.5.0",
>     "@types/react": "^18.3.11",
>     "@types/react-dom": "^18.3.1",
>     "@types/webpack-env": "^1.18.5",
>     "eslint": "^8.57.0",
>     "eslint-config-next": "^14.2.15",
>     "prisma": "^5.21.0",
>     "sass": "^1.79.5",
>     "ts-node": "^10.9.2",
>     "typescript": "^5.6.3"
>   },
>   "prisma": {
>     "Run code below so:": "npx prisma db seed",
>     "seed": "ts-node --compiler-options {\"module\":\"CommonJS\"} src/utils/postgres.ts"
>   }
> }

Compile:
> next dev -p 3005
> 
>   ▲ Next.js 14.2.15
>   - Local:        http://localhost:3005
>   - Environments: .env
> 
>  ✓ Starting...
>  ✓ Ready in 1579ms
>  ○ Compiling /resources/[id] ...
>  ✓ Compiled /resources/[id] in 12.5s (898 modules)
>  GET /resources/30 200 in 13212ms
>  ○ Compiling /_not-found ...
>  ✓ Compiled /_not-found in 940ms (755 modules)
>  GET /_next/static/chunks/app/resources/%5Bid%5D/react-toastify.esm.mjs.map 404 in 1170ms
>  GET /_next/static/chunks/app/resources/react-toastify.esm.mjs.map 404 in 1132ms
>  GET /_next/static/chunks/app/react-toastify.esm.mjs.map 404 in 1158ms

**Comment by Dupflo** [comment] 2024-10-18 08:11
> > Yes in 14.2.15, the error does not occur anymore
> 
> The error still occurs.
> 
> package.json:
> 
> > {
> > "name": "jackdaw",
> > "version": "0.1.0",
> > "private": true,
> > "scripts": {
> > "dev": "next dev -p 3005",
> > "build": "prisma generate && next build",
> > "start": "next start",
> > "lint": "next lint"
> > },
> > "dependencies": {
> > "@prisma/client": "^5.21.0",
> > "animate.css": "^4.1.1",
> > "mobx": "^6.13.5",
> > "mobx-react-lite": "^4.0.7",
> > "next": "^14.2.15",
> > "react": "^18.3.1",
> > "react-dom": "^18.3.1",
> > "react-toastify": "^10.0.6",
> > "zod": "^3.23.8"
> > },
> > "devDependencies": {
> > "@types/node": "^22.5.0",
> > "@types/react": "^18.3.11",
> > "@types/react-dom": "^18.3.1",
> > "@types/webpack-env": "^1.18.5",
> > "eslint": "^8.57.0",
> > "eslint-config-next": "^14.2.15",
> > "prisma": "^5.21.0",
> > "sass": "^1.79.5",
> > "ts-node": "^10.9.2",
> > "typescript": "^5.6.3"
> > },
> > "prisma": {
> > "Run code below so:": "npx prisma db seed",
> > "seed": "ts-node --compiler-options {"module":"CommonJS"} src/utils/postgres.ts"
> > }
> > }
> 
> Compile:
> 
> > next dev -p 3005
> > ▲ Next.js 14.2.15
> > 
> > * Local:        http://localhost:3005
> > * Environments: .env
> > 
> > ✓ Starting...
> > ✓ Ready in 1579ms
> > ○ Compiling /resources/[id] ...
> > ✓ Compiled /resources/[id] in 12.5s (898 modules)
> > GET /resources/30 200 in 13212ms
> > ○ Compiling /_not-found ...
> > ✓ Compiled /_not-found in 940ms (755 modules)
> > GET /_next/static/chunks/app/resources/%5Bid%5D/react-toastify.esm.mjs.map 404 in 1170ms
> > GET /_next/static/chunks/app/resources/react-toastify.esm.mjs.map 404 in 1132ms
> > GET /_next/static/chunks/app/react-toastify.esm.mjs.map 404 in 1158ms

My react-toastify version is  10.0.5, can you try it ?

**Comment by Kila14** [comment] 2024-10-18 08:51
> My react-toastify version is 10.0.5, can you try it ?

Nothing has changed.

**Comment by Kila14** [comment] 2024-10-18 09:20
> Weird, remove .next and node_modules and reinstall it to make sure there is no fragment

The same issue

**Comment by franckadil** [comment] 2024-10-21 15:24
``Same issue, tried all the solutions highlighted above.

using:
~~~
"next": "^14.2.15",
"react": "^18.3.1",
"react-dom": "^18.3.1",
"react-toastify": "^10.0.6",
~~~~

**Comment by Kila14** [comment] 2024-10-30 08:39
The errors have disappeared with this package.json:
```
{
  "name": "jackdaw",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev -p 3005",
    "build": "prisma generate && next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@dnd-kit/core": "^6.1.0",
    "@prisma/client": "^5.21.1",
    "animate.css": "^4.1.1",
    "mobx": "^6.13.5",
    "mobx-react-lite": "^4.0.7",
    "next": "^15.0.2",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-toastify": "^10.0.6",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "@types/node": "^22.8.1",
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "@types/webpack-env": "^1.18.5",
    "eslint": "^9.13.0",
    "eslint-config-next": "^15.0.2",
    "prisma": "^5.21.1",
    "sass": "^1.80.5",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.3"
  },
  "prisma": {
    "Run code below so:": "npx prisma db seed",
    "seed": "ts-node --compiler-options {\"module\":\"CommonJS\"} src/utils/postgres.ts"
  }
}
```

**Comment by saad17shaikh** [comment] 2024-11-06 07:04
Just create a client component like this 
`
"use client";

import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
const ClientSideToast = () => <ToastContainer />;

export default ClientSideToast;

`
and then import it in your layout.tsx
`
// import "react-toastify/dist/ReactToastify.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientSideToast from "@/components/other-components/client-side-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <ClientSideToast />
      </body>
    </html>
  );
}

`
this solved my problem the above solution wasn't working for me

**Comment by artemis-prime** [comment] 2024-11-12 02:32
Sorry, but WTHECK!  Is including a css file rocket science??  Get on this owners!

**Comment by JimmyAG** [comment] 2024-11-16 15:15
Well the issue isn't coming from the library itself, I'm afraid. 
I've just ran into the same issue while working on a side project 

 ```
GET /_next/static/css/app/(frontend)/(auth)/auth/ReactToastify.css.map 404 in 47ms
 GET /_next/static/chunks/app/(frontend)/(auth)/auth/react-toastify.esm.mjs.map 404 in 22ms
 GET /_next/static/chunks/app/(frontend)/(auth)/auth/login/react-toastify.esm.mjs.map 404 in 28ms
```

The problem is coming from the middleware.ts in nextjs
I knew this because It wouldn't show the css files unless it is excluded in the matcher, so it is for the toast css

Here is the matcher I'm using, which fixed the issue for me!
Just add this to your `middleware.ts`, and feel free to adjust it as needed for your own project
```js
export const config = {
  matcher: [
    '/((?!api|_next/static|_next/image|manifest.webmanifest|favicon.ico|sitemap.xml|robots.txt|.*\\.png|.*\\.jpg|.*\\.jpeg$).*)',
  ],
}
```

**Comment by JimmyAG** [comment] 2024-11-23 07:39
> > Well the issue isn't coming from the library itself, I'm afraid. I've just ran into the same issue while working on a side project
> > ```
> > GET /_next/static/css/app/(frontend)/(auth)/auth/ReactToastify.css.map 404 in 47ms
> > GET /_next/static/chunks/app/(frontend)/(auth)/auth/react-toastify.esm.mjs.map 404 in 22ms
> > GET /_next/static/chunks/app/(frontend)/(auth)/auth/login/react-toastify.esm.mjs.map 404 in 28ms
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The problem is coming from the middleware.ts in nextjs I knew this because It wouldn't show the css files unless it is excluded in the matcher, so it is for the toast css, removing the middleware shows the toast!
> > Here is the matcher I'm using, which fixed the issue for me! Just add this to your `middleware.ts`, and feel free to adjust it as needed for your own project
> > ```js
> > export const config = {
> >   matcher: [
> >     '/((?!api|_next/static|_next/image|manifest.webmanifest|favicon.ico|sitemap.xml|robots.txt|.*\\.png|.*\\.jpg|.*\\.jpeg$).*)',
> >   ],
> > }
> > ```
> 
> I don't know the internals/details of this topic's issue but maybe the author of this repo, @fkhadra , could reach out to vercel (if this is the case, that it's related to how Next.js handle things) and ask for some pointers/help... they've got the resources so maybe they can help if @fkhadra is busy.
> 
> This is after all the most commented issue in this repo so I think it deserves some love. I think a lot of people would appreciate it. :)

I agree, but at least I hope that the users who commented on this issue try this out, before reaching out to Vercel!

**Comment by fkhadra** [comment] 2024-11-23 17:01
Thanks for the insight, I'll open an issue/discussion on next repo to see if I could get some pointers. 
Btw, anybody tried to include the css using the injectStyle instead of importing the css file ?

**Comment by fkhadra** [comment] 2024-11-25 20:54
I'm currently planning on releasing the v11. It removes the need to import any css file and most likely it will solve this issue.

**Comment by subvertallchris** [comment] 2024-12-04 17:24
@fkhadra eagerly looking forward to v11! 🙏

**Comment by fkhadra** [comment] 2024-12-16 23:15
Hey, I've released the v11, it is not longer required to import the css file. Please read the release note before upgrading 🙏🏽

**Closed by fkhadra** 2024-12-16 23:15 UTC
