### ISSUE TITLE
React Toastify not recognized as an ES module

### ISSUE THREAD

**Issue by mikebarkmin** [fkhadra/react-toastify#766] opened 2022-05-27 13:27 UTC
**Do you want to request a *feature* or report a *bug*?**

I think this is a bug with the bundle.

**What is the current behavior?**

React Toastify is not recognized as an ES module. The build of an next application with react toastify will fail with the following error. 

```
SyntaxError: Named export 'ToastContainer' not found. The requested module 'react-toastify' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react-toastify';
```

**What is the expected behavior?**

It should not fail with this error and just load the ES module.

**Demo-Repo**

https://github.com/openpatch/patches-nextjs-starter/tree/dcd30554da8c1cd393a8c15be4f2d4c6ae8777c8

**Solution**

I think the filename is not correct. Since this package does not specify, that it is a module via the type field in the package json. The `js` will interpret as a CommonJS module. See here: https://github.com/developit/microbundle#usage-with-typemodule-in-packagejson. 

There are two solutions to the problem:

1. Add type: "module" to the package.json and replace the `js` extension with `cjs` for the CommonJS output.
2. Replace the `js` extension with `mjs` for the ES module output `react-toastify.esm.js`.

**Comment by fkhadra** [comment] 2022-05-29 07:45
Hey @mikebarkmin, were you able to test your fix?

**Comment by mikebarkmin** [comment] 2022-05-29 07:55
@fkhadra I tested the second option and added mjs. This worked fine with nextjs.

**Comment by fkhadra** [comment] 2022-05-29 08:14
Ok, thanks. I'm running a couple of tests with your PR and I will merge it if everything is ok. Thanks a lot!

**Comment by fkhadra** [comment] 2022-05-29 10:04
I've just created a new nextjs app locally and I'm not able to reproduce the issue.

<img width="1011" alt="Screenshot 2022-05-29 at 12 02 54" src="https://user-images.githubusercontent.com/5574267/170862595-b3a2d670-e737-4815-933e-5592966192a5.png">

Also, I don't see react-toastify in the repo you linked https://github.com/openpatch/patches-nextjs-starter/tree/dcd30554da8c1cd393a8c15be4f2d4c6ae8777c8

**Comment by mikebarkmin** [comment] 2022-05-29 10:41
Ok. Then the issue seems to be that I am indirectly importing react-toastify via another library. Maybe in your setup react-toastify was loaded as a CommonJS and in my case react-toastify was loaded as a ES module.

Not using the right file extension lead to issues for other libraries as well:

- https://github.com/react-hook-form/react-hook-form/pull/7262
- https://github.com/prismicio/prismic-react/pull/111

**Comment by fkhadra** [comment] 2022-05-29 14:38
Ok, I'll close the issue for now but keep your PR open. If more people encounter the same issue, I'll use your PR. Thank you

**Closed by fkhadra** 2022-05-29 14:38 UTC
