### ISSUE TITLE
EventManager.js:87 <SHOW_TOAST> Event is not registered. Did you forgot to bind the event ?

### ISSUE THREAD

**Issue by jayar95** [fkhadra/react-toastify#4] opened 2017-04-05 21:18 UTC
There are times I want to show the toast outside of a button click. In these cases, the console will show the following alert: 
EventManager.js:87 <SHOW_TOAST> Event is not registered. Did you forgot to bind the event ?

**Comment by sniphpet** [comment] 2017-04-05 21:28
Hello,

Can you provide me a sample to reproduce it please ?

Thanks

**Comment by jayar95** [comment] 2017-04-11 15:07
Yes! Sorry I forgot to include one originally!

`if(this.props.location.state && this.props.location.state.updatedAccount)
 +			toast('Account Updated! If you published a new account, the initial data pull could take a few minutes.', {
 +				type: toast.TYPE.SUCCESS
 +			});`

**Comment by sniphpet** [comment] 2017-04-11 15:35
Thanks. I'll investigate asap !

**Comment by sniphpet** [comment] 2017-04-11 16:19
I think that you are calling the toast function somewhere in your render method. Right ?

What is happening is that the ToastContainer is not rendered at this time which means that the event won't be bonded.

In your case it will be best to call the toast function inside [componentWillReceiveProps](https://facebook.github.io/react/docs/react-component.html#componentwillreceiveprops):

```javascript
class Foo extends Component {

  componentWillReceiveProps(nextProps) {
    if (nextProps.location.state && nextProps.location.state.updatedAccount)
      toast('Account Updated! If you published a new account, the initial data pull could take a few minutes.', {
        type: toast.TYPE.SUCCESS
      });
  }

  render() {
    return <div>Hello</div>
  }
}

```

**Comment by mtompkins** [comment] 2017-05-12 21:41
As the question is still open I thought I'd share my similar struggle. I'm not trying to hijack the thread here but I thought others might search down this particular error and my addition useful.

I thought the `componentDidMount` would be sufficient but it fails on initial load. Navigating back to the page does fire it off as expected. Any thoughts on what I might be missing?

I have a router **Home** page I'm trying to do a toast with as:

```
export default class Home extends Component {
  componentDidMount() {
    console.log('mounted');
    UpRcvdToast();
  }
  render() {
    return (
      <div>
        <div className={styles.container} data-tid="container">
          <h2>Home</h2>
          <Link to="/counter">to Counter</Link><br />
          <Link to="/foo">to Foo</Link><br />
        </div>
      </div>
    );
  }
}
```
and the function lives in an import as:
```
export function UpRcvdToast() {
  log.debug('Trigger UpRcvdMsg');
  toast(<UpRcvdMsg />, UpRcvdOpts);
}
```

**Comment by fkhadra** [comment] 2017-05-12 22:06
I'm now able to reproduce the issue using react router. I'm on it.

**Comment by mtompkins** [comment] 2017-05-12 22:08
Thanks so much - love this little bit of code btw - thanks for sharing!

**Comment by fkhadra** [comment] 2017-05-12 22:10
Glad you like it. Don't forget to pick the latest version :grin:

**Comment by fkhadra** [comment] 2017-05-15 10:44
FYI, I have a fix for that issue. I'll try to make the patch for this week or the next one.

**Comment by mtompkins** [comment] 2017-05-15 11:25
Awesome - thanks for the update. Will test it a bit when released.

**Comment by fkhadra** [comment] 2017-05-28 20:25
This has been fixed with release 1.6.0

**Closed by fkhadra** 2017-05-28 20:25 UTC
Labels: bug, enhancement

**Comment by realneeraj** [comment] 2018-02-22 13:01
@fkhadra 
toast.success() dont seem to fire up in my react-redux project when I successfully login. Could you please help?

When API returns 401, toast.error() works fine. But when API return 200, I'm doing a route change to /dashboard. That's when toast.success('You have been logged in successfully!') does not seem to fire up.

development branch - https://github.com/realneeraj/react.git

**Comment by fkhadra** [comment] 2018-02-22 13:11
@realneeraj sure. I'll have a look later on when I'm back from work.

**Comment by realneeraj** [comment] 2018-02-22 13:47
Thank you!

**Comment by fkhadra** [comment] 2018-02-22 20:29
@realneeraj on login success, the ToastContainer is calling `componentWillUnmount`:
<img width="662" alt="screen shot 2018-02-22 at 21 13 43" src="https://user-images.githubusercontent.com/5574267/36562057-030623f2-1816-11e8-91b6-7997babe5bb4.png">
Inside ToastContainer's  `componentWillUnmount` I clean all events listeners. 

There is something that I don't understand:
- `componentWillUnmount` is called but the component is still mounted
- I expected `componentDidMount` or `componentWillMount` to be called but it's not the case

I'm wondering how it's possible that componentWillUmount is called and the component is not removed from the rendering tree.

**Comment by realneeraj** [comment] 2018-02-23 05:08
I'm pretty new to React and I'm not really sure I understand it well though.

I had just following your anwser here https://github.com/fkhadra/react-toastify/issues/117 - to put <ToastContainer /> in App level. Is it because of this that even after componentWillUnmount is called, the component is still mounted (I'm just suspecting and I can we completely wrong here).

**Comment by realneeraj** [comment] 2018-02-23 05:46
@fkhadra - My bad brother. I had accidentally placed another <ToastContainer /> in the Login.js Component. Removing it solved the issue. All is well now.

Really appreciate your kind responses and help. react-toastify is a great piece of code.

Thank you once again! Cheers :)
