### ISSUE TITLE
Implementation in react redux - css not loading

### ISSUE THREAD

**Issue by trekiteasy** [fkhadra/react-toastify#309] opened 2019-01-24 16:31 UTC
**Do you want to request a *feature* or report a *bug*?**
This is probably more about me not integrating correctly in a redux react app ? (Even though I looked at your example and feel I'm doing exactly what you are doing...

**What is the current behavior?**
The Toast css isn't loaded at all (I need to write the css class myself with position: fixed and z-index: 9999 in order to see it - styleless).

The app has a search bar and I was willing to open a toast when a search starts.
The toast is here (in the DOM), but without CSS it is not visible unless I write a custom css class.
What I am missing ?

The code :

App.js
```import React from 'react';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

class App extends React.Component {
  render () {
    return (
      <div>
        <ToastContainer />
       <!-- Other containers -->
      </div>
    );
  }
}
```

/* Rest of the App.js file */

actions.js
```
import { toast } from 'react-toastify';

export const UNIFIED_SEARCH_START = 'UNIFIED_SEARCH_START';

export function unifiedSearchStart () {
  toast.success('Unified search start');
  return {
    type: UNIFIED_SEARCH_START,
    payload: true
  };
}

export function unifiedSearch (terms) {
  return dispatch => {
    dispatch(unifiedSearchStart());
    /* do other things here */
  }
}
```

**What is the expected behavior?**
Was expecting to have the css with this

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react 16.3.2 - chrome - MacOS

**Comment by haihoang20** [comment] 2019-01-25 05:46
This is also happening to me. If I use just `toast` then nothing appears on the screen at all. If I use `ToastContainer` then plain text gets rendered on the page where the container is.

**Comment by merelj** [comment] 2019-01-25 14:01
same here

**Comment by fkhadra** [comment] 2019-01-25 14:20
Hello,

Could you reproduce the issue on codesanbox?

Did you render  the `ToastContainer` at the root of your app ? Where did you import the css?

Thanks

**Comment by trekiteasy** [comment] 2019-01-25 15:40
> Did you render the `ToastContainer` at the root of your app ? Where did you import the css?
Yes, ToastContainer is rendered at the root of my app (as in App.js above).
I import the css only in App.js (as above), in the same file containing my ToastContainer.

**Comment by trekiteasy** [comment] 2019-01-28 16:50
@RenatRysaev I think you nailed it... but you lost me at the same time !
Could you give a bit more detail on what you actually did and in which files ?
Thanks in advance !

**Comment by bhanushukla** [comment] 2019-04-09 17:06
The import will not work with css-loader in place. 
You should import it where you have your global css loaded.

I did `@import '../node_modules/react-toastify/dist/ReactToastify.min.css';` in my global css so that it is unescaped from CSS modules.

**Comment by fkhadra** [comment] 2019-05-17 19:26
I'll close the issue since it's more related to build tools than the lib itself.

**Closed by fkhadra** 2019-05-17 19:26 UTC
Labels: question
