### ISSUE TITLE
[Bug] React 19: React.createElement: type is invalid 

### ISSUE THREAD

**Issue by malte94** [fkhadra/react-toastify#1193] opened 2024-12-19 21:49 UTC
Hey there! :)

**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

The application crashes after upgrading to React 19 whenever a toast is outputted.

React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Error Component Stack

`toast.info("hello");`

**What is the expected behavior?**

The application shall not crash.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 19, Chrome, Win 11

Worked fine with React 18.

**Comment by fkhadra** [comment] 2024-12-19 22:22
Hey @malte94 the issue is likely on your side. Could you share a snippet so I could help you troubleshoot your issue

**Comment by malte94** [comment] 2024-12-19 23:13
Hi Fadi, Thank you for your prompt reply. Here's a snippet:

```
import { toast } from 'react-toastify';
    async function createCustomer(customer) {
        try {
            if (!customer.customer_number) {
                return toast.info("Bitte eine Kundennummer eingeben.");
            }

            if (!customer.lastname) {
                return toast.info("Bitte einen Nachnamen eingeben.");
            }
            const res = await axios.post('/api/customers/create', { customer });
            await loadCustomers(true);
            toast.success("Der Kunde wurde angelegt.");
            return res.data;
        } catch (error) {
            console.error("Error creating customer:", error);
            throw error;
        }
    }
```

**Comment by fkhadra** [comment] 2024-12-19 23:59
Do you think you could reproduce the issue here https://stackblitz.com/edit/vitejs-vite-qfvbga15?file=src%2FApp.tsx ?

**Comment by malte94** [comment] 2024-12-20 17:34
@fkhadra Thank you for your help. It generally works perfectly on Stackblitz with React 19.

However, in our application, we encounter a crash when upgrading from React 18 to React 19, and the issue appears to be "related" (though not necessarily caused) to react-toastify. Any function executes correctly when the toast is removed from it.

Once I have resolved the issue, I will provide an update here.

**Comment by fkhadra** [comment] 2024-12-20 18:49
Alright @malte94, i'll close this issue for now. Feel free to ping me whenever it's sorted out on your side.

**Closed as completed by fkhadra** 2024-12-20 18:49 UTC
Labels: Reproduction Needed

**Comment by Basti007** [comment] 2024-12-30 02:24
Hi,
I am facing the same issue.
I also tried inside the sandbox but everything works fine there. Not sure where this problem comes from and I already tried to copy most of my code inside the sandbox but it just works fine. Maybe someone knows where this problem comes from.

This seems pretty weird to me, but maybe some code samples can help identify this issue.
ToastContainer.tsx:
```tsx
import React, { FC } from 'react'
import { useThemeMode } from '@metronic/theme/partials'
import { ToastContainer as ToastifyContainer } from 'react-toastify'

const ToastContainer: FC = () => {
  const { mode } = useThemeMode()

  return (
    <ToastifyContainer
      position='top-right'
      autoClose={7500}
      limit={10}
      hideProgressBar={false}
      newestOnTop={false}
      closeOnClick
      rtl={false}
      pauseOnFocusLoss
      draggable
      pauseOnHover
      theme={mode === 'dark' ? 'dark' : 'light'}
      closeButton={({ closeToast }) => (
        <button className='btn btn-xs btn-icon btn-light' onClick={closeToast}>
          <i className='ki-outline ki-cross'>
          </i>
        </button>
      )}
    />
  )
}

export { ToastContainer }
```

Toast.tsx:
```tsx
import React from 'react'
import { useTranslation } from '../hooks'

export interface ToastProps {
  message?: string
  moreDetails?: string
}

const Toast = ({
  message,
  moreDetails,
}: ToastProps) => {
  const { trans } = useTranslation()

  // If no message is provided, a generic message is displayed
  message = message || trans('BASIC.ERRORS.GENERIC')

  return (
    <>
      <p className={
        moreDetails
          ? 'font-bold text-sm mb-0'
          : 'font-normal mb-0 text-sm'
      }>{message}</p>
      {moreDetails && (
        <p className='text-gray-500 text-xs mt-1'>{moreDetails}</p>
      )}
    </>
  )
}

export { Toast }
```

NotificationUtils.tsx:
```tsx
import { Id, toast, ToastOptions } from 'react-toastify'
import { ToastProps, Toast } from '../components/Toast'

const notify = (props: ToastProps, toastProps?: ToastOptions): Id => toast(<Toast message={props.message}
                                                                                  moreDetails={props.moreDetails} />, toastProps)
notify.success = (props: ToastProps, toastProps?: ToastOptions): Id => toast.success(<Toast message={props.message}
                                                                                            moreDetails={props.moreDetails} />, toastProps)
notify.error = (props: ToastProps, toastProps?: ToastOptions): Id => toast.error(<Toast message={props.message}
                                                                                        moreDetails={props.moreDetails} />, toastProps)
notify.info = (props: ToastProps, toastProps?: ToastOptions): Id => toast.info(<Toast message={props.message}
                                                                                      moreDetails={props.moreDetails} />, toastProps)
notify.warning = (props: ToastProps, toastProps?: ToastOptions): Id => toast.warning(<Toast message={props.message}
                                                                                            moreDetails={props.moreDetails} />, toastProps)

export { notify }
```

Kind regards

Just a quick edit: Even when using the default toast function and a default ToastContainer, the problem still persists.

**Comment by fkhadra** [comment] 2024-12-30 02:39
@Basti007 could you share you package.json file? At least dependencies and devDependencies

**Comment by Basti007** [comment] 2024-12-30 02:57
Yes sure, here you go:
```json
{
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc -b && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
		"@adamscybot/react-leaflet-component-marker": "^2.0.2",
    "@formatjs/intl-pluralrules": "5.2.4",
    "@formatjs/intl-relativetimeformat": "11.2.4",
    "@fortawesome/fontawesome-free": "6.1.1",
    "@popperjs/core": "^2.11.6",
		"@tanstack/react-query": "^5.62.11",
    "@tanstack/react-query-devtools": "^5.4.3",
		"@testing-library/react": "^16.1.0",
    "animate.css": "4.1.1",
    "apexcharts": "3.35.0",
    "axios": "^1.7.7",
    "clsx": "^2.1.0",
    "formik": "2.2.9",
    "framer-motion": "^11.2.14",
		"get-orientation": "^1.1.2",
		"leaflet": "^1.9.4",
    "line-awesome": "1.3.0",
    "lodash": "^4.17.21",
    "nouislider": "15.5.1",
		"react": "19.0.0",
    "react-apexcharts": "1.4.0",
		"react-dom": "19.0.0",
		"react-easy-crop": "^5.1.0",
    "react-helmet": "^6.1.0",
		"react-intl": "^7.0.4",
		"react-leaflet": "^5.0.0",
    "react-router-dom": "6.3.0",
		"react-select": "^5.9.0",
		"react-toastify": "^11.0.2",
		"react-tooltip": "^5.28.0",
    "react-topbar-progress-indicator": "4.1.1",
    "socicon": "3.0.5",
    "tw-bootstrap-grid-optimizer": "^1.0.2",
    "yup": "^1.0.0"
  },
  "devDependencies": {
    "@tanstack/eslint-plugin-query": "^5.0.5",
    "@testing-library/jest-dom": "5.16.4",
    "@testing-library/user-event": "14.4.3",
    "@types/chart.js": "2.9.37",
    "@types/jest": "29.5.2",
		"@types/leaflet": "^1.9.15",
    "@types/lodash": "^4.17.10",
    "@types/node": "20.3.1",
		"@types/react": "19.0.0",
    "@types/react-copy-to-clipboard": "5.0.2",
		"@types/react-dom": "19.0.0",
    "@types/react-helmet": "^6.1.8",
    "@types/react-table": "^7.7.9",
    "@types/sass-loader": "8.0.3",
    "@typescript-eslint/eslint-plugin": "^7.13.1",
    "@typescript-eslint/parser": "^7.13.1",
    "@vitejs/plugin-react": "^4.3.1",
    "@vitejs/plugin-react-swc": "^3.6.0",
    "autoprefixer": "^10.4.19",
    "css-loader": "6.7.1",
    "del": "7.0.0",
    "eslint": "^8.57.0",
    "eslint-plugin-react-hooks": "^4.6.2",
    "eslint-plugin-react-refresh": "^0.4.7",
    "mini-css-extract-plugin": "2.6.1",
    "mini-svg-data-uri": "^1.4.4",
    "postcss": "^8.4.39",
    "postcss-import": "^16.1.0",
    "postcss-loader": "^8.1.1",
    "postcss-nesting": "^12.1.5",
    "postcss-preset-env": "^9.5.15",
    "remove-files-webpack-plugin": "^1.5.0",
    "rtlcss-webpack-plugin": "4.0.7",
    "sass": "1.55.0",
    "sass-loader": "13.2.0",
    "tailwindcss": "^3.4.4",
    "typescript": "^5.3.3",
    "vite": "^5.3.1"
  }
}

```

**Comment by fkhadra** [comment] 2024-12-30 03:12
Hard to tell what's wrong, I suspect the issue is either coming from another dependency or there is a mix between some named exports and defaults export. Is your repo a public one by any chance?

**Comment by malte94** [comment] 2024-12-31 10:29
Good morning,

We do not have much dependencies in common, but those are:

animate.css, axios, sass, vite

**Comment by Basti007** [comment] 2025-01-02 22:25
> Hard to tell what's wrong, I suspect the issue is either coming from another dependency or there is a mix between some named exports and defaults export. Is your repo a public one by any chance?

Our repository is sadly not public. You are probably right that the issue is coming from another dependency. Maybe I can try to create a sandbox with all depedencies and my code snippets and see if that works.



> Good morning,
> 
> We do not have much dependencies in common, but those are:
> 
> animate.css, axios, sass, vite

The only thing that might cause the error is vite (at least thats my guess). But that seems to be a bit weird.

**Comment by Basti007** [comment] 2025-01-02 23:06
Update: I downgraded to React 18 and now everything works fine.
I will probably not upgrade to React 19 yet 😅

Thanks for your help, I appreciate that!

**Comment by fkhadra** [comment] 2025-01-02 23:08
Alright thanks for keeping me updated.

**Comment by davisperezg** [comment] 2025-01-07 03:57
I also had the same thing happen to me, in my case I solved it by updating the react-toastify version, I had it on version 9, I just had to update to the latest version 11.0.2.

**Comment by Nellak2017** [comment] 2025-02-23 20:49
Thank you! Solved my issue. I was at Toastify version 9 and it worked on older versions of React and Next.js and Storybook, but when I updated it stopped working. The solution was literally to update Toastify to version 11.
