### ISSUE TITLE
[Bug]: Unable to select text inside inputs when a toast is open

### ISSUE THREAD

**Issue by felixmosh** [fkhadra/react-toastify#550] opened 2020-12-20 09:31 UTC
**What is the current behavior?**
When the toast is open & `draggable={true}` it is not possible to select the text inside inputs with **mouse drag**.

https://user-images.githubusercontent.com/9304194/102709941-78ea4700-42b7-11eb-8a68-768fb6725b1c.mov

Steps to reproduce:
1. open codesandbox https://codesandbox.io/s/react-react-toastify-working-forked-bu95r
2. write some text inside the input
3. click to open a toast
4. try to select the text inside of the input using mouse drag

**What is the expected behavior?**
It should not prevent mouse drag outside of the toast it self.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React v17
react-toastify v6.2.0 (it is not reproduces in react-toastify 6.1.0)

**Comment by AmooHashem** [comment] 2020-12-20 13:56
Isn't it a normal behavior?

**Comment by felixmosh** [comment] 2020-12-20 13:59
Why is it a normal behavior? 
The `draggble` must apply only of the toast, not the entire page.

Think about a call center app, which shows the caller details in a toast, which always affects the entire page.

**Comment by fkhadra** [comment] 2020-12-20 14:11
@felixmosh fair point. It seems like a regression to me as you were not able to reproduce the issue with v6.1 . I'll look at it asap.

**Comment by felixmosh** [comment] 2020-12-20 14:12
Thanx 🙏🏼

**Comment by fkhadra** [comment] 2020-12-20 21:33
@felixmosh, is it the expected behavior? 


https://user-images.githubusercontent.com/5574267/102724939-5f76e880-4313-11eb-8c8e-53ae4350be2f.mov

**Comment by felixmosh** [comment] 2020-12-21 05:40
It can be fixed with usage of css user-select: none.

**Comment by DaleyKD** [comment] 2021-01-15 16:18
Seeing the tag "Merged in next", does this mean that this is fixed in the next release?

**Comment by fkhadra** [comment] 2021-01-15 16:36
Indeed. The PR is open I'm almost done.

**Comment by DaleyKD** [comment] 2021-01-15 17:17
@fkhadra : THANK YOU! This bug came up via QA for our product, and would be great for it to be resolved before we go live. Thank you for such an awesome library.

**Closed** 2021-01-25 14:45 UTC
Labels: Merged in next
