### ISSUE TITLE
Typings generated for Toast position constants are of type string not ToastPosition

### ISSUE THREAD

**Issue by hisuwh** [fkhadra/react-toastify#486] opened 2020-06-01 11:06 UTC
There is a bug in the typings generated for the the positions constants `toast.POSITION.TOP_LEFT` etc.  The typings for these are `string` but the options object for the toast functions are expecting a `ToastPosition` which is a string union of the possible values

For example the following the code produces and Typescript compilation error:
```ts
import { toast } from "react-toastify"

toast.error("My toast message", { position: toast.POSITION.TOP_CENTER });
```

**What is the expected behavior?**

I would not expect to get a compilation error using the built in constants of the package.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
N/A

**Comment by fkhadra** [comment] 2020-07-02 17:29
Hey @hisuwh,

The issue is fixed in release 6.0.7.

**Closed by fkhadra** 2020-07-02 17:29 UTC
